### ISSUE TITLE
Falling Block doesn't rendering, when it's velocity is straight up or down BUG

### ISSUE THREAD

**Issue by Dreig-Michihi** [Tectato/Vectorientation#3]
By the way, the mod is fantastic!
I hope you won't abandon it

**Comment by Tectato** [comment]
Does this happen at any speed or just when the block has fallen a long way and is going considerably fast? In the latter case this is a known bug which i didnt get around to fixing yet

**Comment by Tectato** [comment]
Fixed in latest release
