### ISSUE TITLE
Minecraft with the mod can't load

### ISSUE THREAD

**Issue by xleb-normal** [Tectato/Vectorientation#8]
Minecraft version 1.21.1
Mod version 1.1 for 1.21.x
When starting minecraft, the loading screen hangs indefinitely
log https://mclo.gs/9N30BTi

**Comment by Tectato** [comment]
you're using the 1.21.3 version of the mod, which is incompatible with 1.21.1

**Comment by xleb-normal** [comment]
> you're using the 1.21.3 version of the mod, which is incompatible with 1.21.1

Can you change the game version to 1.21.3 in modrinth, the 1.21.x value might confuse people and they might accidentally install an incompatible version with their client.
![image](https://github.com/user-attachments/assets/f9217d2f-fd3c-4e5d-b53d-1b2071890a5b)

**Comment by Tectato** [comment]
Fixed
